name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull baominh/nodejs-ci-cd:latest
      - name: Delete Old docker container
        run: sudo docker rm -f nodejs-ci-cd-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 80:4000 --name nodejs-ci-cd-container baominh/nodejs-ci-cd