name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Pull Docker image
        run: sudo docker pull baominh/nodejs-ci-cd:latest
      - name: Delete Old docker container
        run: sudo docker rm -f nodejs-ci-cd-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 80:4000 --name nodejs-ci-cd-container baominh/nodejs-ci-cd